---
- name: Install extra ifupdown helpers
  ansible.builtin.apt:
    pkg:
      - rdnssd
      - resolvconf
      - vlan
    install_recommends: false

- name: Configure ifupdown network interfaces
  ansible.builtin.template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - confirm network change
    - restart networking

- name: Create interfaces.d directory
  ansible.builtin.file:
    path: /etc/network/interfaces.d/
    state: directory
    mode: "0755"

- name: Configure additional ifupdown network interfaces
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/network/interfaces.d/{{ item | basename }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob:
    - "../../../templates/interfaces/{{ inventory_hostname }}/*"
  notify:
    - confirm network change
    - restart networking

- name: Configure ifupdown hooks
  ansible.builtin.template:
    src: "hook"
    dest: >-
      {{ "/etc/network/if-" + item.phase + ".d/" + item.name }}
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
  loop: "{{ network_hooks }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - confirm network change
    - restart networking

- name: Configure /etc/default/networking
  ansible.builtin.template:
    src: "ifupdown"
    dest: "/etc/default/networking"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  when: network_ifupdown_config != ""
  notify: restart ifupdown-wait-online

- name: Enable or disable ifupdown-wait-online systemd service
  ansible.builtin.systemd:
    name: "ifupdown-wait-online.service"
    enabled: "true"
  when: network_systemd_wait_online
