---

- name: Check for netplan
  stat:
    path: /usr/sbin/netplan
  register: check_for_netplan

- name: Configure networking interfaces with ifupdown
  include_tasks: ifupdown.yml
  when: "not check_for_netplan.stat.exists"

- name: Configure networking interfaces with netplan
  include_tasks: netplan.yml
  when: "check_for_netplan.stat.exists"
