---

- name: Install bridge-utils package if bridges are configured
  apt:
    pkg:
      - bridge-utils
    state: present
  when: "network_interfaces | selectattr('bridge_ports', 'defined') | list"

- name: Check for netplan
  stat:
    path: /usr/sbin/netplan
  register: check_for_netplan

- name: Check if this device has any wireless interfaces
  ansible.builtin.shell: |
    find /sys/class/ieee80211/ -type l
    ip -all netns exec find /sys/class/ieee80211/ -type l | grep "/sys/class/ieee80211/"
  register: check_for_wireless
  changed_when: false
  failed_when: false

- name: Configure wireless devices
  ansible.builtin.import_tasks: wifi.yml
  when: "check_for_wireless.stdout_lines | length > 0"

- name: Configure networking interfaces with ifupdown
  ansible.builtin.import_tasks: ifupdown.yml
  when: "not check_for_netplan.stat.exists"

- name: Configure networking interfaces with netplan
  ansible.builtin.import_tasks: netplan.yml
  when: "check_for_netplan.stat.exists"
