---

- name: Gather package facts
  package_facts:
    manager: auto

- include: ifupdown.yml
  when: "'ifupdown' in ansible_facts.packages"

- include: netplan.yml
  when: "'netplan.io' in ansible_facts.packages"
