---
- name: Configure loopback interface
  template:
    src: interfaces
    dest: /etc/network/interfaces
  notify: restart networking

- name: Install networking dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - resolvconf

- name: Configure additional network interfaces
  template:
    src: "{{ item }}"
    dest: "/etc/network/interfaces.d/{{ item | basename }}"
  with_fileglob:
    - "../../../templates/interfaces/{{ inventory_hostname }}/*"
  notify: restart networking
