---
# Using /sys interface for rfkill rather than rfkill command directly as it
# seemed easier to parse:
#     https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-rfkill
#
# Persistence for rfkill config is provided by systemd-rfkill

- name: Install wireless packages if wireless interfaces are configured
  ansible.builtin.apt:
    pkg: "{{ wireless_packages }}"
    install_recommends: false
  when: "network_interfaces | selectattr('access_points', 'defined') | list"

- name: Get enabled wireless devices
  ansible.builtin.set_fact:
    enabled_wireless_devices: >-
      {{ network_interfaces | selectattr('access_points', 'defined') | map(attribute="name")
         | intersect(wireless_devices) }}

- name: Get disabled wireless devices
  ansible.builtin.set_fact:
    disabled_wireless_devices: >-
      {{ wireless_devices | difference(enabled_wireless_devices) }}

- name: Get desired rfkill software block state
  ansible.builtin.set_fact:
    _rfkill_state: >-
      {{ (
           enabled_wireless_devices
           | community.general.json_query("[].{name: @, value: '0'}")
         ) + (
           disabled_wireless_devices
           | community.general.json_query("[].{name: @, value: '1'}")
         ) }}

- name: Set rfkill software block state
  ansible.builtin.shell: |
    set -euo pipefail

    if [ -d "/sys/class/net/{{ item.name }}/phy80211" ]; then
      while read -r rfkill_dir; do
        if [ "$(cat "${rfkill_dir}/soft")" != "{{ item.value }}" ]; then
            echo "{{ item.value }}" | tee "${rfkill_dir}/soft"
            echo "{{ item.name }} state changed to {{ item.value }}"
        fi
      done <<< "$(find /sys/class/net/{{ item.name }}/phy80211/ -maxdepth 1 -name "rfkill*")"
    fi
  args:
    executable: /bin/bash
  register: _configure_rfkill
  changed_when: "'changed' in _configure_rfkill.stdout"
  loop: "{{ _rfkill_state }}"
  loop_control:
    label: "{{ item.name }}={{ 'blocked' if item.value == '1' else 'unblocked' }}"

- name: Set rfkill software block state in network namespaces
  ansible.builtin.shell: |
    set -euo pipefail

    ip -all netns exec bash -c '
      if [ -d "/sys/class/net/{{ item.name }}/phy80211" ]; then
        while read -r rfkill_dir; do
          if [ "$(cat "${rfkill_dir}/soft")" != "{{ item.value }}" ]; then
              echo "{{ item.value }}" | tee "${rfkill_dir}/soft"
              echo "{{ item.name }} state changed to {{ item.value }}"
          fi
        done <<< "$(find /sys/class/net/{{ item.name }}/phy80211/ -maxdepth 1 -name "rfkill*")"
      fi'
  args:
    executable: /bin/bash
  when: "network_namespaces | length >= 1"
  register: _netns_configure_rfkill
  changed_when: "'changed' in _netns_configure_rfkill.stdout"
  loop: "{{ _rfkill_state }}"
  loop_control:
    label: "{{ item.name }}={{ 'blocked' if item.value == '1' else 'unblocked' }}"
