---
- name: confirm network change
  ansible.builtin.pause:
    prompt: Please check the network configuration changes. Press enter to apply or ctrl-c to stop
  when: network_wait_on_change

- name: restart networking
  ansible.builtin.service:
    name: networking.service
    state: restarted

- name: netplan apply
  ansible.builtin.command:
    cmd: netplan apply
