---
- name: Get current network state
  ansible.builtin.command:
    cmd: ip address show
  register: _network_state
  changed_when: false
  when: network_wait_on_change
  listen: confirm network change

- name: Prompt before changing network configuration
  ansible.builtin.pause:
    prompt: |-
      Current network state:

      {{ _network_state.stdout }}

      Please check the network configuration changes. Press enter to apply or ctrl-c to stop
  when: network_wait_on_change
  listen: confirm network change

- name: restart networking
  ansible.builtin.service:
    name: networking.service
    state: restarted

- name: restart ifupdown-wait-online
  ansible.builtin.service:
    name: ifupdown-wait-online.service
    state: restarted

- name: netplan apply
  ansible.builtin.command:
    cmd: netplan apply
