---
- name: Prepare
  hosts: all
  tasks:
    - name: "Install ifupdown on Debian"
      ansible.builtin.apt:
        pkg:
          - "ifupdown"
      when: ansible_distribution == "Debian"

    - name: "Install netplan on Ubuntu"
      ansible.builtin.apt:
        pkg:
          - "udev"
          - "netplan.io"
      when: ansible_distribution == "Ubuntu"

    - name: "Check for virtual network interface"
      ansible.builtin.command: "ip link show dev eno1"
      changed_when: false
      failed_when:
        - _check_virtual_network_interface.rc != 0
        - "'does not exist' not in _check_virtual_network_interface.stderr"
      register: _check_virtual_network_interface

    - name: "Add virtual network interface"
      ansible.builtin.command: "ip tuntap add eno1 mode tap"
      when: _check_virtual_network_interface.rc != 0

- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.networking"
      ansible.builtin.include_role:
        name: "wandansible.networking"
      vars:
        network_wait_on_change: false
        network_interfaces:
          - name: "eno1"
            waitonboot: true
            families:
              - name: ipv4
                type: dhcp
              - name: ipv6
                type: auto
