---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.networking"
      ansible.builtin.include_role:
        name: "wandansible.networking"
      vars:
        network_wait_on_change: false
        network_interfaces:
          - name: "eno1"
            waitonboot: true
            families:
              - name: ipv4
                type: dhcp
              - name: ipv6
                type: auto
