---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DOCKER_IMAGE:-ubuntu:latest}
    pre_build_image: false
    override_command: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/tmp/resolv.conf:/etc/resolv.conf
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
